// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecureBucket extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'secure-bucket:index:SecureBucket';

    /**
     * Returns true if the given object is an instance of SecureBucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecureBucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecureBucket.__pulumiType;
    }

    declare public /*out*/ readonly bucketArn: pulumi.Output<string>;
    declare public /*out*/ readonly bucketId: pulumi.Output<string>;
    declare public /*out*/ readonly bucketName: pulumi.Output<string>;
    declare public readonly kmsKeyArn: pulumi.Output<string>;
    declare public /*out*/ readonly kmsKeyId: pulumi.Output<string>;

    /**
     * Create a SecureBucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecureBucketArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.customerName === undefined && !opts.urn) {
                throw new Error("Missing required property 'customerName'");
            }
            resourceInputs["allowedRegions"] = args?.allowedRegions;
            resourceInputs["customerName"] = args?.customerName;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["kmsKeyArn"] = args?.kmsKeyArn;
            resourceInputs["owner"] = args?.owner;
            resourceInputs["projectName"] = args?.projectName;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["bucketArn"] = undefined /*out*/;
            resourceInputs["bucketId"] = undefined /*out*/;
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["kmsKeyId"] = undefined /*out*/;
        } else {
            resourceInputs["bucketArn"] = undefined /*out*/;
            resourceInputs["bucketId"] = undefined /*out*/;
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["kmsKeyArn"] = undefined /*out*/;
            resourceInputs["kmsKeyId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecureBucket.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a SecureBucket resource.
 */
export interface SecureBucketArgs {
    allowedRegions?: string[];
    customerName: pulumi.Input<string>;
    environment?: pulumi.Input<string>;
    kmsKeyArn?: pulumi.Input<string>;
    owner?: pulumi.Input<string>;
    projectName?: string;
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
